syntax on
set list
set listchars+=leadmultispace:\▏\ \ \ 
set listchars+=trail:•,extends:⟩,precedes:⟨
set showmatch
set ruler
set number
set scrolloff=8

set ignorecase
set smartcase
set incsearch
set undodir=~/.vim_undo
set undofile

set smarttab
set expandtab
set shiftwidth=4
set ts=4 sw=4
nnoremap <tab> <c-w>

set background=dark
colorscheme gruvbox

source ~/.vimrc
