syntax on
set list
set listchars=trail:•,extends:⟩,precedes:⟨,leadmultispace:•
set showmatch
set ruler
set number
set scrolloff=8

set smarttab
set expandtab
set shiftwidth=4
set ts=4 sw=4
source ~/.vimrc
